import type { Metadata } from 'next';
import { Lato } from 'next/font/google';
import './globals.sass';

const lato = Lato({
  weight: ['400'],
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProps = Readonly<{
  children: React.ReactNode
}>;

const RootLayout = (props: RootLayoutProps) => (
  <html lang="en">
    <body className={lato.className}>{props.children}</body>
  </html>
);

export default RootLayout;
