import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { clsx } from 'clsx';
import './globals.sass';
import { getTheme } from '@/actions/settings-actions';
import { Theme } from '@/types/settings';
import Head from 'next/head';

const inter = Inter({
  weight: 'variable',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProps = Readonly<{
  children: React.ReactNode
}>;

const RootLayout = (props: RootLayoutProps) => {
  const theme: Theme = getTheme();

  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, viewport-fit=cover"/> 
      </Head>
      <body
        className={clsx(
          inter.className,
          'bg-grey3',
          theme === Theme.DARK && 'theme-dark',
          theme === Theme.LIGHT && 'theme-light',
          theme === Theme.AUTO && 'theme-auto'
        )}
      >
        {props.children}
      </body>
    </html>
  );
};

export default RootLayout;
