name: Build & Publish Web Client Image

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch for deployment (staging or main)'
        required: true
        default: staging

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build & Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag
        id: vars
        run: |
          echo "sha=${GITHUB_SHA}" >> $GITHUB_OUTPUT
          if [[ "${{ github.event.inputs.branch }}" == "main" ]]; then
            echo "branch_tag=production" >> $GITHUB_OUTPUT
          else
            echo "branch_tag=staging" >> $GITHUB_OUTPUT
          fi

      - name: Build Docker image
        run: |
          IMAGE=ghcr.io/nikelaz/bw-web-client
          docker build -t $IMAGE:${{ steps.vars.outputs.sha }} -f Dockerfile.prod .
          docker tag $IMAGE:${{ steps.vars.outputs.sha }} $IMAGE:${{ steps.vars.outputs.branch_tag }}

      - name: Push Docker images
        run: |
          IMAGE=ghcr.io/nikelaz/bw-web-client
          docker push $IMAGE:${{ steps.vars.outputs.sha }}
          docker push $IMAGE:${{ steps.vars.outputs.branch_tag }}
